# Generated by Django 4.2.4 on 2024-05-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0003_historicalperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPerformance',
        ),
    ]
